# Generated by Django 5.0.14 on 2026-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_paid_only_launch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
