# generator/models.py
"""
Updated to link WebsiteGeneration to a User.

Migration note:
  After adding the user FK (nullable), run:
    python manage.py makemigrations generator
    python manage.py migrate
"""
from django.conf import settings
from django.core.validators import MinLengthValidator
from django.db import models


class WebsiteGeneration(models.Model):
    """
    Stores a single AI website generation request + result.

    Each record is owned by a User (or anonymous if user is None).
    Queries must always filter by user to enforce project isolation.
    """
    # ── Ownership  ← NEW
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,       # nullable so anonymous legacy rows still exist
        blank=True,
        related_name="generations",
        db_index=True,
    )

    # ── Content
    prompt = models.TextField(
        validators=[MinLengthValidator(10)],
        help_text="Original user prompt",
    )
    spec_json = models.JSONField(
        null=True, blank=True,
        help_text="Structured spec extracted from the prompt",
    )
    generated_code = models.TextField(
        blank=True, default="",
        help_text="Final generated HTML/CSS/JS",
    )
    pages_json = models.JSONField(
        null=True, blank=True, default=dict,
        help_text="Multi-page output: {slug: html, …}. Empty dict for single-page sites.",
    )
    title = models.CharField(
        max_length=255, default="New Website", blank=True,
        help_text="Project display name (editable by user)",
    )

    # ── Preview thumbnail (generated async by Celery task after creation)
    preview_image = models.ImageField(
        upload_to='previews/',
        null=True, blank=True,
        help_text="WebP thumbnail generated by Playwright — set by generate_preview Celery task",
    )

    # ── Metadata
    tokens_used = models.IntegerField(
        default=0,
        help_text="Total tokens consumed (spec + generation)",
    )
    ip_address = models.GenericIPAddressField(
        null=True, blank=True,
        help_text="Requester IP address",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name        = "Website Generation"
        verbose_name_plural = "Website Generations"
        indexes = [
            models.Index(fields=["-created_at"]),
            models.Index(fields=["ip_address"]),
            models.Index(fields=["user", "-created_at"]),   # ← NEW — fast per-user list
        ]

    def __str__(self):
        owner = self.user.email if self.user else self.ip_address
        return f"Generation #{self.id} [{owner}] — {self.prompt[:60]}…"


class APIUsageLog(models.Model):
    """Immutable log entry for every API request (success or failure)."""

    # ── Ownership  ← NEW (nullable for backward compat)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name="usage_logs",
        db_index=True,
    )

    ip_address    = models.GenericIPAddressField(help_text="Requester IP")
    endpoint      = models.CharField(max_length=100)
    tokens_used   = models.IntegerField(default=0)
    success       = models.BooleanField(default=True)
    error_message = models.TextField(blank=True, null=True)
    timestamp     = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering            = ["-timestamp"]
        verbose_name        = "API Usage Log"
        verbose_name_plural = "API Usage Logs"
        indexes = [
            models.Index(fields=["-timestamp"]),
            models.Index(fields=["ip_address", "-timestamp"]),
            models.Index(fields=["endpoint", "-timestamp"]),
            models.Index(fields=["user", "-timestamp"]),   # ← NEW
        ]

    def __str__(self):
        status = "✓" if self.success else "✗"
        return f"{status} {self.ip_address} → {self.endpoint} @ {self.timestamp:%Y-%m-%d %H:%M}"