# Generated by Django 5.0.1 on 2026-02-25 05:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(help_text="Requester IP")),
                ("endpoint", models.CharField(max_length=100)),
                ("tokens_used", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Usage Log",
                "verbose_name_plural": "API Usage Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="generator_a_timesta_42a316_idx"
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"],
                        name="generator_a_ip_addr_1ef377_idx",
                    ),
                    models.Index(
                        fields=["endpoint", "-timestamp"],
                        name="generator_a_endpoin_840ccd_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="generator_a_user_id_c01393_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WebsiteGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="Original user prompt",
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                (
                    "spec_json",
                    models.JSONField(
                        blank=True,
                        help_text="Structured spec extracted from the prompt",
                        null=True,
                    ),
                ),
                (
                    "generated_code",
                    models.TextField(
                        blank=True, default="", help_text="Final generated HTML/CSS/JS"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="New Website",
                        help_text="Project display name (editable by user)",
                        max_length=255,
                    ),
                ),
                (
                    "tokens_used",
                    models.IntegerField(
                        default=0, help_text="Total tokens consumed (spec + generation)"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Requester IP address", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Website Generation",
                "verbose_name_plural": "Website Generations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="generator_w_created_32f46c_idx"
                    ),
                    models.Index(
                        fields=["ip_address"], name="generator_w_ip_addr_a4d70e_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="generator_w_user_id_19f039_idx",
                    ),
                ],
            },
        ),
    ]
