# Generated by Django 5.0.14 on 2026-03-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitegeneration",
            name="pages_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Multi-page output: {slug: html, …}. Empty dict for single-page sites.",
                null=True,
            ),
        ),
    ]
