# Generated by Django 5.0.14 on 2026-03-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0002_websitegeneration_pages_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitegeneration",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                help_text="WebP thumbnail generated by Playwright — set by generate_preview Celery task",
                null=True,
                upload_to="previews/",
            ),
        ),
    ]
