# Generated by Django 5.0.14 on 2026-03-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0003_websitegeneration_preview_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="websitegeneration",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="websitegeneration",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
