# Generated by Django 5.0.14 on 2026-03-21 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("generator", "0004_soft_delete_website_generation"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.TextField(help_text="Full HTML at the time of the snapshot"),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable label, e.g. 'Generated' or 'Edit #3'",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="generator.websitegeneration",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["generation", "-created_at"],
                        name="generator_w_generat_c90275_idx",
                    )
                ],
            },
        ),
    ]
